fixed templates

diff --git a/roles/slurm-provision/templates/slurm_provision.sh.j2 b/roles/slurm-provision/templates/slurm_provision.sh.j2
--- a/roles/slurm-provision/templates/slurm_provision.sh.j2
+++ b/roles/slurm-provision/templates/slurm_provision.sh.j2
@@ -1,33 +1,39 @@
 #!/bin/sh
 
-CVL_HOME="/cvl/home"
+HOME_DIR="/cvl/home"
 user_list=($(getent passwd | cut -d ":" -f1))
 log_file="/root/slurm.log"
 
 for user in ${user_list[*]}; do
-    uid=$(id -u ${user})
-    gid=$(id -g ${user})
-    user_home=${CVL_HOME}/${user}
-    if [[ ! -d ${user_home} && ${uid} -gt 1000 ]]; then
-        mkdir -p ${user_home}
-        cp -r /etc/skel/* ${user_home}
-        chown -R ${uid}:${gid} ${user_home}
-        chmod 700 ${user_home}
+    {% if project_check is defined %}
+        run=$(id ${user} | grep {{ project_check }})
+    {% else %}
+        run="1"
+    {% endif %}
+    if [ ! -z "${run}" ]; then
+        uid=$(id -u ${user})
+        gid=$(id -g ${user})
+        user_home=${HOME_DIR}/${user}
+        if [[ ! -d ${user_home} && ${uid} -gt 1000 ]]; then
+            cp -r /etc/skel ${user_home}
+            chown -R ${uid}:${gid} ${user_home}
+            chmod 700 ${user_home}
 
-        account={{ projectname }}
-        cluster={{ clustername }}
+            account={{ projectname }}
+            cluster={{ clustername }}
 
-        find=$(sacctmgr list cluster ${cluster} | grep ${cluster})
-        if [ -z "${find}" ]; then
-            su slurm -c "sacctmgr -i add cluster ${cluster}" || { echo "error to create cluster ${cluster}" >> ${log_file} && exit 1; }
-        fi
-        find=$(sacctmgr list account ${account} | grep ${account})
-        if [ -z "${find}" ]; then
-            su slurm -c "sacctmgr -i add account ${account} Description=CVL Organization=monash cluster=${cluster}" || { echo "error to create account ${account}" >> ${log_file} && exit 1; }
-        fi
-        find=$(sacctmgr list user ${username} | grep ${username})
-        if [ -z "${find}" ]; then
-            su slurm -c "sacctmgr -i add user ${username} account=${account} cluster=${cluster}" || { echo "error to create user ${username}" >> ${log_file} && exit 1; }
+            find=$(sacctmgr list cluster ${cluster} | grep ${cluster})
+            if [ -z "${find}" ]; then
+                su slurm -c "sacctmgr -i add cluster ${cluster}" || { echo "error to create cluster ${cluster}" >> ${log_file} && exit 1; }
+            fi
+            find=$(sacctmgr list account ${account} | grep ${account})
+            if [ -z "${find}" ]; then
+                su slurm -c "sacctmgr -i add account ${account} Description=CVL Organization=monash cluster=${cluster}" || { echo "error to create account ${account}" >> ${log_file} && exit 1; }
+            fi
+            find=$(sacctmgr list user ${user} | grep ${user})
+            if [ -z "${find}" ]; then
+                su slurm -c "sacctmgr -i add user ${user} account=${account} cluster=${cluster}" || { echo "error to create user ${user}" >> ${log_file} && exit 1; }
+            fi
         fi
     fi
 done
