the provision role now uses flock and has some help finding sacctmgr if its not in the path

diff --git a/roles/provision/templates/provision.sh.j2 b/roles/provision/templates/provision.sh.j2
--- a/roles/provision/templates/provision.sh.j2
+++ b/roles/provision/templates/provision.sh.j2
@@ -3,6 +3,8 @@
 HOME_DIR={{ home_dir }}
 user_list=($(getent passwd | cut -d ":" -f1))
 log_file="/root/slurm.log"
+export PATH=$PATH:{{ slurm_dir }}/bin
+sacctmgr=$( which sacctmgr )
 
 for user in ${user_list[*]}; do
     {% if project_check is defined %}
@@ -24,15 +26,15 @@ for user in ${user_list[*]}; do
 
             find=$(sacctmgr list cluster ${cluster} | grep ${cluster})
             if [ -z "${find}" ]; then
-                su slurm -c "sacctmgr -i add cluster ${cluster}" || { echo "error to create cluster ${cluster}" >> ${log_file} && exit 1; }
+                su slurm -c "$sacctmgr -i add cluster ${cluster}" || { echo "error to create cluster ${cluster}" >> ${log_file} && exit 1; }
             fi
             find=$(sacctmgr list account ${account} | grep ${account})
             if [ -z "${find}" ]; then
-                su slurm -c "sacctmgr -i add account ${account} Description=CVL Organization=monash cluster=${cluster}" || { echo "error to create account ${account}" >> ${log_file} && exit 1; }
+                su slurm -c "$sacctmgr -i add account ${account} Description=CVL Organization=monash cluster=${cluster}" || { echo "error to create account ${account}" >> ${log_file} && exit 1; }
             fi
             find=$(sacctmgr list user ${user} | grep ${user})
             if [ -z "${find}" ]; then
-                su slurm -c "sacctmgr -i add user ${user} account=${account} cluster=${cluster}" || { echo "error to create user ${user}" >> ${log_file} && exit 1; }
+                su slurm -c "$sacctmgr -i add user ${user} account=${account} cluster=${cluster}" || { echo "error to create user ${user}" >> ${log_file} && exit 1; }
             fi
         fi
     fi
